# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'shilai2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for shilai2

pod 'SnapKit'
pod 'Moya'
pod 'SwiftyJSON'
pod 'JKSwiftExtension'
pod 'TZImagePickerController'
pod 'Realm'
pod 'RealmSwift'

end
